###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-mayikt-weixin
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka


####swagger相关配置
swagger:
  base-package: com.mayikt.weixin.service
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目”
  version: 1.1
  terms-of-service-url: www.wxcs.cn
  contact:
    name: 比以往快10倍的登录方式
    email: 416660553@qq.com


###微信端口8200 做集群8201  8202  8203
###会员端口8300 做集群8301  8302  8303
###便于区分