logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://192.168.170.129:8080/eureka
server:
  port: 9800


  
spring:
  application:
    name: app-mayikt-spike
  redis:
    host: 120.78.137.82
   # password: 123456
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
###数据库相关连接      
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meite_spike?autoReconnect=true&characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
  rabbitmq:
  ####连接地址
    host: 192.168.170.129
   ####端口号
    port: 5672
   ####账号
    username: guest
   ####密码
    password: guest
   ### 地址
    virtual-host: /admin_host
    ###开启消息确认机制 confirms
    publisher-confirms: true
    publisher-returns: true
  